export enum WALLET_TRANSACTION_TYPE {
  RECHARGE = 'RECHARGE',
  CALL_DEDUCTION = 'CALL_DEDUCTION',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  DISTRIBUTOR_ISSUANCE = 'DISTRIBUTOR_ISSUANCE',
  REFUND = 'REFUND',
}

export enum TRANSFER_KIND {
  PEER = 'PEER',
  ADMIN_RESERVE_GRANT = 'ADMIN_RESERVE_GRANT',
}
